version: '3'

services:
  ms:
    container_name: awezomestore_purchases_ms
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - "bd"
    volumes:
      - .:/usr/src/app
  bd:
    container_name: awezomestore_purchases_db
    image: mongo
    ports: 
      - "4040:27017"
